#!/usr/bin/env sh

VLC=$(command -v cvlc)
XSET=$(command -v xset)

if [ -z "${VLC_SOURCE_URL}" ]; then
    echo "Source URL not defined (VLC_SOURCE_URL)"
    exit 1
fi

if [ -z "${VLC_BITRATE}" ]; then
    VLC_BITRATE=1024
fi

if [ -z "${VLC_CACHE}" ]; then
    VLC_CACHE=1024
fi

if [ -z "${VLC_THREADS}" ]; then
    VLC_THREADS=$(nproc --all)
fi

if [ -z "${VLC_ASPECT_RATIO}" ]; then
    VLC_ASPECT_RATIO=16:9
fi

if [ -z "${VLC_ADAPTIVE_WIDTH}" ]; then
    VLC_ADAPTIVE_WIDTH=1280
fi

if [ -z "${VLC_ADAPTIVE_HEIGHT}" ]; then
    VLC_ADAPTIVE_HEIGHT=720
fi

if [ -z "${VLC_ADAPTIVE_BITRATE}" ]; then
    VLC_ADAPTIVE_BITRATE=2048
fi

if [ -z "${VLC_ADAPTIVE_LOGIC}" ]; then
    VLC_ADAPTIVE_LOGIC=highest
fi

if [ -z "${VLC_VERBOSE}" ]; then
    VLC_VERBOSE=0
fi

if [ -z "${VLC_ZOOM}" ]; then
    VLC_ZOOM=1
fi

if [ -z "${VLC_DISPLAY}" ]; then
    VLC_DISPLAY=:0
fi

if [ -z "${VLC_AVCODEC_OPTIONS}" ]; then
    # VLC_AVCODEC_OPTIONS="--avcodec-dr --avcodec-corrupted --avcodec-hurry-up --avcodec-skip-frame=1 --avcodec-skip-idct=1 --avcodec-fast --avcodec-threads=${VLC_THREADS} --sout-avcodec-strict=-2"
    VLC_AVCODEC_OPTIONS=""
fi

# Allow VLC to run as root
# shellcheck disable=SC2086
sed -i 's/geteuid/getppid/' ${VLC}

# Remove the X server lock file so ours starts cleanly
rm /tmp/.X0-lock &>/dev/null || true

# Create XDG_RUNTIME_DIR
if [ -d "${HOME}/.cache" ]; then
    rm -Rf ~/.cache
fi
mkdir -pv ~/.cache/xdgr
export XDG_RUNTIME_DIR=$PATH:~/.cache/xdgr

# Set the display to use
export DISPLAY=${VLC_DISPLAY}

# Set the DBUS address for sending around system messages
if [ -f "/host/run/dbus/system_bus_socket" ]; then
    export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
fi

# Start the desktop manager
echo "STARTING X"
startx -- -nocursor &
CHILD_STARTX=$!

# TODO: work out how to detect X has started
sleep 10

SHUTTING_DOWN=false
_term() {
    SHUTTING_DOWN=true
    echo "👋 Shutting down..."
    if [ -n "${CHILD_VLC}" ]; then
        kill -TERM "$CHILD_VLC" 2>/dev/null
    fi
    if [ -n "${CHILD_STARTX}" ]; then
        kill -TERM "$CHILD_STARTX" 2>/dev/null
    fi
}

trap _term INT TERM

# Start the VLC media player
VLC_COMMAND="${VLC} --verbose=${VLC_VERBOSE} --x11-display ${DISPLAY} ${VLC_AVCODEC_OPTIONS} --zoom ${VLC_ZOOM} --no-repeat --no-loop --network-caching=${VLC_CACHE} --drop-late-frames --skip-frames --adaptive-logic=${VLC_ADAPTIVE_LOGIC} --adaptive-maxwidth=${VLC_ADAPTIVE_WIDTH} --adaptive-maxheight=${VLC_ADAPTIVE_HEIGHT} --adaptive-bw=${VLC_ADAPTIVE_BITRATE} --no-play-and-pause --play-and-exit --no-disable-screensaver ${VLC_SOURCE_URL} vlc://quit"
while :; do
    ${XSET} s off
    ${XSET} -dpms
    ${XSET} s noblank

    # Hide the cursor
    unclutter -display ${DISPLAY} -idle 0.1 &

    echo "📺 Starting VLC"
    echo "🖥 ${VLC_COMMAND}"
    # shellcheck disable=SC2086
    nice -n -20 ${VLC_COMMAND} &
    CHILD_VLC=$!
    echo "🆔 VLC Running as PID ${CHILD_VLC}"
    wait "$CHILD_VLC"
    echo "👋 VLC Stream Finished"
    if [ "$SHUTTING_DOWN" = true ]; then
        break
    fi
done
