#!/usr/bin/env sh

VLC=$(command -v cvlc)
XSET=$(command -v xset)

if [ -z "${VLC_SOURCE_URL}" ]; then
    echo "Source URL not defined (VLC_SOURCE_URL)"
    exit 1
fi

if [ -z "${VLC_BITRATE}" ]; then
    VLC_BITRATE=1024
fi

if [ -z "${VLC_CACHE}" ]; then
    VLC_CACHE=1024
fi

if [ -z "${VLC_THREADS}" ]; then
    VLC_THREADS=$(nproc --all)
fi

if [ -z "${VLC_ASPECT_RATIO}" ]; then
    VLC_ASPECT_RATIO=16:9
fi

if [ -z "${VLC_ADAPTIVE_WIDTH}" ]; then
    VLC_ADAPTIVE_WIDTH=1280
fi

if [ -z "${VLC_ADAPTIVE_HEIGHT}" ]; then
    VLC_ADAPTIVE_HEIGHT=720
fi

if [ -z "${VLC_ADAPTIVE_BITRATE}" ]; then
    VLC_ADAPTIVE_BITRATE=2048
fi

if [ -z "${VLC_ADAPTIVE_LOGIC}" ]; then
    VLC_ADAPTIVE_LOGIC=highest
fi

if [ -z "${VLC_VERBOSE}" ]; then
    VLC_VERBOSE=0
fi

if [ -z "${VLC_ZOOM}" ]; then
    VLC_ZOOM=1
fi

if [ -z "${VLC_DISPLAY}" ]; then
    VLC_DISPLAY=:0
fi

if [ -z "${VLC_AVCODEC_OPTIONS}" ]; then
    # VLC_AVCODEC_OPTIONS="--avcodec-dr --avcodec-corrupted --avcodec-hurry-up --avcodec-skip-frame=1 --avcodec-skip-idct=1 --avcodec-fast --avcodec-threads=${VLC_THREADS} --sout-avcodec-strict=-2"
    VLC_AVCODEC_OPTIONS=""
fi

# Allow VLC to run as root
sed -i 's/geteuid/getppid/' /usr/bin/vlc

# Remove the X server lock file so ours starts cleanly
rm /tmp/.X0-lock &>/dev/null || true

# Create XDG_RUNTIME_DIR
if [ -d "${HOME}/.cache" ]; then
    rm -Rf ~/.cache
fi
mkdir -pv ~/.cache/xdgr
export XDG_RUNTIME_DIR=$PATH:~/.cache/xdgr

# Set the display to use
export DISPLAY=${VLC_DISPLAY}

# Set the DBUS address for sending around system messages
if [ -f "/host/run/dbus/system_bus_socket" ]; then
    export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
fi

# Start the desktop manager
echo "STARTING X"
startx -- -nocursor &
CHILD_STARTX=$!

# TODO: work out how to detect X has started
sleep 5

${XSET} s off
${XSET} -dpms
${XSET} s noblank

# Hide the cursor
unclutter -display ${DISPLAY} -idle 0.1 &

_term() { 
  echo "👋 Shutting down..."
  if [ -n "${CHILD_VLC}" ]; then
    kill -TERM "$CHILD_VLC" 2>/dev/null
  fi
  if [ -n "${CHILD_STARTX}" ]; then
    kill -TERM "$CHILD_STARTX" 2>/dev/null
  fi
}

trap _term SIGTERM

# Start the VLC media player
# /usr/bin/cvlc -q --no-osd -L -f --no-video-title-show --x11-display ${DISPLAY} --zoom 2 --no-repeat --no-loop --drop-late-frames --skip-frames --play-and-exit rtp://@234.0.1.255:1234 vlc://quit
VLC_COMMAND="${VLC} --verbose=${VLC_VERBOSE} --x11-display ${DISPLAY} --no-disable-screensaver ${VLC_AVCODEC_OPTIONS} --zoom ${VLC_ZOOM} --no-repeat --no-loop --network-caching=${VLC_CACHE} --drop-late-frames --skip-frames --play-and-exit --adaptive-logic=${VLC_ADAPTIVE_LOGIC} --adaptive-maxwidth=${VLC_ADAPTIVE_WIDTH} --adaptive-maxheight=${VLC_ADAPTIVE_HEIGHT} --adaptive-bw=${VLC_ADAPTIVE_BITRATE} ${VLC_SOURCE_URL} vlc://quit"
echo "Starting: ${VLC_COMMAND}"
nice -n -20 ${RCLONECMD} &
CHILD_VLC=$!
echo "VLC Running as PID ${CHILD_VLC}"
wait "$CHILD_VLC"